### ISSUE TITLE
Release build is broken

### ISSUE THREAD

**Issue by yitsushi** [yitsushi/totp-cli#51]
Will be fixed. Until then you can install with

```
go install github.com/yitsushi/totp-cli@v1.2.0
```

**Comment by NightSling** [comment]
Solved with PR #53

**Comment by yitsushi** [comment]
No it does not fix that. That PR is changing only `README.md` and that was and those changes (that was fixed) was introduced in https://github.com/yitsushi/totp-cli/pull/52 (5 days ago), while this is about release binaries.

See https://github.com/yitsushi/totp-cli/releases/tag/v1.2.1, it does not have release build.
